---
apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: rdspostgresql
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: default  # aws-provider-config
  forProvider:
    region: eu-west-1
    dbInstanceClass: db.t3.micro
    masterUsername: masteruser
    allocatedStorage: 20
    engine: postgres
    engineVersion: "9.6"
    skipFinalSnapshotBeforeDeletion: true
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: aws-rdspostgresql-conn
